---
output: 
  pdf_document:
    latex_engine: pdflatex
    template: template.tex
geometry: margin=1in

title: "POLS 155-01: International Political Economy"
author: Sergio Béjar-López
date: "San Jose State University, Spring 2021"

email: "sergio.bejar@sjsu.edu"
web: "sergiobejar.com"
officehours: "Tuesday 3:00-5:00 p.m. & by appointment (Zoom)"
office: "453 Clark Hall"
classroom: "*online*"
classhours: "Asynchronous"

fontfamily: mathpazo
fontsize: 11pt
header-includes:
   - \linespread{1.05}
---

# Catalog Course Description

This course examines how states, international and multinational bodies, and global social movements shape trade, financial, and labor relations. Topics include: international trade and protectionism, the International Monetary Fund and the World Bank, regional integration, and transnational corporations.

# Detailed Course Description

This course will help students to develop a conceptual and empirical background that is necessary to understand globalization and the changes taking place in the international economy.  Our main focus will be to critically analyze some of the most important issues in the current international economic system.  At a broader level, we will study topics such as the politics of trade policy, foreign direct investment, financial crises, and the future of the global economic system.   More specifically, we will analyze the politics of trade conflict at the GATT/WTO, trade reforms in developing countries, the role of multinational corporations in the world economy, the role of international financial institutions like the IMF, and debates over outsourcing and financial crises.  For each topic, we will analyze different theoretical explanations and a variety of historical and contemporary examples. 

*This is an Online Education course. All assignments and exams will be conducted over the Internet. Students are responsible for their own access to the Internet and computer resources.*


# Expectations and Activities

Success in this class will depend upon your ability to: (1) think critically; (2) read and write University-level English prose; (3) develop an ability to understand and systematically apply the basics of research design; (4) work  independently and in group when needed. 

I expect students to: 

1) read this syllabus carefully,
2) log on to the class web site a minimum of four times each week,
3) read all assigned materials,
4) watch lectures,
5) submit assignments and exams on time,

DO NOT enroll in an online course if you know that you are going to be away from your Internet access for more than 5 or 6 days during the length of the course.  Unless you have an extenuating circumstance,  you have to submit all the assignments by the deadline.  

Please note that students are responsible for their own Internet access and computing resources. A loss of connectivity is not an excuse for late assignments. Some Internet service providers (ISPs) are notorious for inferior, unreliable service. In previous semesters, students have lost Internet connectivity in the middle of exams. Students who wait until the last possible moment to submit an assignment also run the risk of an unanticipated service disruption that prevents timely submission. 

# Faculty Webpage and MYSJSU Communication
I will post announcements on Canvas on a regular basis. They will appear on your dashboard when you log in and/or will be sent to you directly through your preferred method of notification from Canvas. Please make sure to check them regularly, as they will contain any important information about upcoming projects or class concerns. 

In this course we will use the CONVERSATIONS feature on the help corner (located in navigation links) to send email for private messages. You can either check your messages in the Canvas system or set your notifications to your preferred method of contact. Please check your messages regularly. 

I receive many emails from students everyday, and I try to respond to all of them in a timely manner.  An email is a formal communication between you and your professor, and it thus should be addressed properly.  For my students, I am Dr. Bejar or Dr. Bejar-Lopez.  Please keep this in mind when you send me an email.  **I will not respond to emails that are not properly addressed.**

# Creating an Environment of Mutual Respect

This class is a partnership between you, your classmates and your professor. Together, we will build a supportive, respective, and productive environment to learn and to explore challenging questions about International Political Economy. Building this kind of environment requires mutual respect.

What do I expect from you, to create an environment of mutual respect? I expect you to complete the readings and watch all the posted lectures.  I also expect professional behavior in the class and to remain engaged throughout the semester.  Lack of interest or engagement is likely to be reflected in your grade.  

What can you expect from me? You can expect me to be tirelessly enthusiastic and to work hard for you, both in this semester and in future semesters if needed. I encourage all of you to stop by my virtual office hours, even if you don’t have a question and just would like to chat about the class, life after SJSU or life in general. You can reach me best via email at <sergio.bejar@sjsu.edu>. 


# Department of Political Science Learning Outcomes

1. Breadth: Students should possess a broad knowledge of the theory and methods of the various branches of the discipline.
2. Application and Disciplinary Methods: Students should be able to formulate research questions, engage in systematic literature searches using primary and secondary sources, evaluate research studies, and critically analyze and interpret influential political texts. Students should be able to apply these techniques to identify, understand, and analyze domestic and international political issues and organizations.
3. Communication Skills: Students should master basic competencies in oral and written communication skills and be able to apply these skills in the context of political science. This means communicating effectively about politics and/or public administration, public policy, and law.
4. Citizenship: Students should acquire an understanding of the role of the citizen in local, state, national, and global contexts and appreciate the importance of lifelong participation in political processes.


# Course Learning Outcomes 

Upon successful completion of this course, students will be able to: 

1. Understand how politics and economics intersect to produce different policies and outcomes (assessed with quizzes, discussion boards, and exams);
2. Identify the most important issues in the current economic system (assessed through quizzes, discussion boards, exams and group policy briefs);
3. Evaluate the outcomes of globalization and other economic policies (assessed through discussion bords and group policy briefs);
4. Compare and contrast different theoretical explanations of phenomena occurring in the international economy (assessed through exams, discussion boards and group policy briefs).


# E-mail Policy

I am usually quick to respond to student e-mails. However, student e-mails tend to do several things that try my patience. I have a new policy, effective Spring 2021, that outlines why I will not respond to certain e-mails students send. Multiple rationales follow.

1. The student could answer his/her own inquiry by reading the syllabus.
2. The student missed assignments or exams. I do not need to know the exact reason for a missed assignment or exam. Students with excusable reasons are responsible for giving me a note *in hard copy* that documents the reason for the missed class. 
3. The student wants to know what topics have been covered in class. The answer is always "you missed what was on the syllabus."
4. The student is protesting a grade without reference to specific points of objection. These e-mails tend to be expressive utility on the part of the student and do not require a response from me. Students interested in improving their knowledge of material should see me during office hours.
6. The student is requesting an extension on an assignment for which the syllabus already established the deadline. The answer is always "no".
7. The student is ["grade grubbing"](https://www.math.uh.edu/~tomforde/GradeGrubbing.html) or asking to round up a grade. The answer is always "no".
8. The student is asking for an extra credit opportunity, a request that amounts to more grading for the professor. The answer is "no".

# Course Workload Expectations: Succeeding in a Four-Unit Course

SJSU classes are designed such that in order to be successful, it is expected that students will spend a minimum of forty-five hours for each unit of credit (normally three hours per unit per week), including preparing for class, participating in course activities, completing assignments, and so on. Because this is a four-unit course, you can expect to spend a minimum of nine hours per week, in addition to time spent in class, on scheduled tutorials, assignments, or activities. This additional unit will allow for more in-depth investigation and engagement with course topics. Careful time management will help you keep up with readings and assignments and enable you to be successful in all of your courses. More details about student workload can be found in University Policy S12-3 at <http://www.sjsu.edu/senate/docs/S12-3.pdf>.


# Course Readings

There is NO required textbook for the course given that the lectures will be asynchronous. That said, I use the following text book as a reference for my lectures: Thomas Oatley, International Political Economy: Interests and Institutions in the Global Economy, 6th ed. (New York: Pearson, 2019). As noted above, this book is optional since I primarily rely on my lecture notes in power-point format for instruction and for the exams as well as the assignments. Although the book is optional, you are more than welcome to buy the book at [Amazon](https://www.amazon.com/International-Political-Economy-Thomas-Oatley/dp/1138490741) if you prefer. In addition to the Thomas Oatley textbook, you are required to read several newspaper articles (online) from CNN Business, CNBC, FOX business, Financial times and so on. You will also have to read and comment on magazine articles or essays from primarily Foreign Affairs, Foreign Policy, the Economist, and other journal-length articles written by academics. You do not have to read the entire journal article unless you want to. In fact, I will provide the page numbers in the journal-length articles that you are expected to read for each class. The reading load for this course is thus fairly light. 

Because the reading load is less, I expect students to read the material carefully and participate constructively in the required Canvas Board Discussions. The power-point lecture slides as well as readings will be available prior to the related class via Canvas and my email messages via Canvas.

# Assignment Weights and Due Dates 

| **Assignment**         | **Weight**             | 
|:--: | :--: | :--: |
| Discussion Boards | 5 x 6% each = 30%  |           
| Group Policy Briefs| 2 x 12.5% each = 25%|           
| Exams             | 2 x 12.5% each = 25% |           
| Quizes            | 5 X 3%  each = 15% |  
|Twitter Engagement | 5% |


# Description of Assignments

**Discussion Boards:**  Students will participate in 5 graded discussion boards (there will be other non-graded boards). In each graded discussion you will be expected to make 3 posts: your initial post (minimum 200 words) and replies to at least two of your classmates (minimum 100 words each).  

The nature of these posts varies.  But you should expect to get questions on the documnetaries and short videos that you are required to watch as well as on the newspaper and magazine articles that are part of your coursework.  Your postings should be well written and clearly address the issues being discussed. I expect each writing assignment to have: (1) A clear introduction that addresses directly the question posed by the instructor; (2) A body of factual examples that support your thesis; these examples may be drawn from either the assigned readings or footnoted sources researched independently by the student; (3) Appropriate source citations; plagiarized threads will be penalized. (4) A succinct concluding paragraph. Your responses must be posted by the deadline specified on Canvas. .

If I have some concerns or comments about your thread, I will post a response. My comments are intended to help you improve your threads. If you respond to my comments, you may earn additional points. In order to earn a perfect score, you generally have to post an excellent thread the first time around and by the assigned deadline. In addition, you must respond to the threads of at least two other students 24 hrs. after the deadline.

**Group Policy Briefs:** Once the final roster of the class is available, I will randomly assign you to a working group (or team).  As a team, you will craft two (2) policy briefs on topics that are currently relevant in the field of International Political Economy.  Each brief should be 1,000 words long. 

You should use the following template to write your two-page policy briefing. 

1. Bottom line: Your policy briefing should offer a recommended course of action for the case study. 
2. Coherent Story: Your briefing should have an introduction, body, and conclusions, just like a paper. 
3. Introduction: What is the problem? Why is it important? What is your one-sentence bottom-line? 
4. Body: You should explicitly identify your policy recommendations and their expected effect. Why is your proposed course of action better than alternative policy solutions? Make sure to outline concrete, alternative actions and present supporting evidence for your policy choice. 
5. Conclusion: What are the broader implications of your recommendations? 

The topics of these policy briefs are:

1. Bitcoin and the Future of the International Monetary System. 
2. The Political Economy of the COVID-19 Crisis. 

**Quizzes:** There will be 5 quizzes.  Each of them will ask questions about the video lecture presentation(s) of the different modules. Success in these quizzes is simple: watch the lectures, take notes, pay attention and review your notes before the quizz.  See course calendar below for due dates.  *Late quizzes –even a second late- will receive a zero.*

**Exams:** Students will take two(2) mid-term exams.  These exams will not be cummulative and are likely to include a combination of multiple choice, short answer and essay questions. See course calendar below for dates. 

Both exams will be administered on Canvas. They will be open-notes and open-book exams, but you will not be allowed to collaborate with other students in completing them. Both exams will be timed. *Late exams –even a second late- will receive a zero.*

**Twitter Engament:** Extant research suggests that learning in online classes is enhanced when students participate in discussions outside the usual class platform.  I am thus going to actively use my Twitter account **@Prof_Bejar** to tweet (or retweet) stuff that is relevant to our class. This is what you need to do to easily earn 5% of your final grade:

1. Open a Twitter account if you do not have one.  You are more than welcome to create an account that is exclusive for our class.
2. Follow my account **@Prof_Bejar**. 
3. Check Twitter often and look for tweets (or retweets) with the hashtag #pols155. 
4. Engage in discussion with your professor and other classmates.  I am teaching three different classes this semester.  You are welcome to participate in discussion of other classes, but this is not required.
5. Invite your family, friends, coworkers, etc. to join the IPE fun on Twitter. While I am primarily interested in helping my students learn, I would not mind if we create an inclusive environment where people outside our class get information about the international economic system and/or politics in general.
6. The more you participate in our discussions, the better your grade will be. 

# Policy on Late Work

**Discussion board (initial posts):** initial posts can be submitted late but will incur a 25% penalty for each started 24-hour period (starting at 5:01pm on the day they are due). This means that you have 72 hrs. before your response receives automatically a 0. 

**Discussion board (replies to classmates):** no late replies to classmates are allowed. The thread will close at 5:01pm on the day replies is due and no further submissions will be allowed.

**Group Policy Briefs:** your briefs will be penalized 25% for each started 24-hour period (starting at 5:01pm). 

**Exams and quizzes:** exam and quiz make-ups are only given in cases of medical or family emergencies, in accordance with the university’s policy on excused absences. In these cases, you MUST notify me before the exam and proper documentation must be provided.

# Grading Scale 

| Grade | Percentage |
| :----| :-------:  |
| A plus| 98-100% |
| A | 94-97.9% |
| A minus| 90-93.9% |
| B plus | 87-89.9%|
| B | 84-86.9% |
| B minus| 80-83.9% |
| C plus | 77-79.9%|
| C | 74-76.9% |
| C minus| 70-73.9% |
| D plus | 67-69.9%|
| D | 64-66.9% |
| D minus| 60-63.9% |
| F | 0-59.9% |

# Public Sharing of Instructor Material

Students are prohibited from distributing, sharing, or posting class lectures, slides, exams, or any other instructional materials. Materials created by the instructor for the course (syllabi, lectures and lecture notes, presentations, exams, etc.) are copyrighted by the instructor. [University policy S12-7](https://www.sjsu.edu/senate/docs/S12-7.pdf) is
in place to protect the privacy of students in the course, as well as to maintain academic integrity through reducing the instances of cheating. Students who record, distribute, or post these materials will be referred to the Student Conduct and Ethical Development office. Unauthorized recording may violate university and state law. It is the responsibility of students that require special accommodations or assistive technology due to a disability to notify the instructor.

# Academic Dishonesty

Students who are suspected of cheating during an exam/quiz/assignment will be referred to the Student Conduct and Ethical Development office and depending on the severity of the conduct, will receive an  F in the course. Grade Forgiveness does not apply to courses for which the original grade was the result of a finding of academic dishonesty.

# Course Schedule (Subject to Change with Fair Notice)

| **Module** | **Dates** | **Topics, Readings and Assignments**|
| :-----:| :-------:| :------|
| 1| Jan 27 - Jan 29 | **Introduction**|
|||1. Syllabus |
|||2. Watch introductory video (Canvas)|
|||3. Listen to [Brexit Podcast](http://www.npr.org/sections/money/2016/06/22/483142244/episode-707-brexit)
|||**Non-graded discussion board due Jan, 29th (5 pm)** |
|||**Syllabus Quiz due Jan, 29th (5 pm)**|
||||
|2|February 1- February 5| **Perspectives on IPE**|
|||1. Read Bernanke. 2006. Read from bottom of page 1 (“A short history of global economic integration”) to the bottom of page 4.|
|||2. Read Keohane and Nye. 2000. Read pages 1 to 4.|
|||3. Watch the [video](https://www.youtube.com/watch?v=OkBYeKAsbxg)|
|||**Discussion Board #1 due February, 5 (5 pm)**|
||||
|3|February 8 - February 19| **Politics of International Trade 1**|
|||1. Read [Lincicome](https://www.cato.org/publications/commentary/case-free-trade)|
|||2. Read [Perry](https://www.aei.org/carpe-diem/rent-seeking-a-significant-cost-of-protectionism-that-doesnt-show-up-in-the-standard-economic-analysis-of-tariffs/)|
|||3. Read [Freeland](http://blogs.reuters.com/chrystia-freeland/2011/07/01/winners-and-losers-in-the-apple-economy/)|
|||4. Cotton Wars [Podcast](http://www.npr.org/blogs/money/2013/05/03/180912847/episode-224-the-cotton-wars)|
|||**Respond to Classmates' Posts by February 8th, (5pm)**|
|||**Quiz #2 due February 12th (5pm)**|
|||**Discussion Board #2 due February, 19th (5pm)**|
||||
|4|February 22 - March 5| **Politics of International Trade 2**|
|||1. Read Milner and Kubota (see Canvas), pages 107-111 and 115-118|
|||2. Read [Harwood](https://www.cnbc.com/2019/06/05/5-reasons-income-inequality-has-become-a-major-political-issue.html)|
|||3. Read [Ortiz-Ospina](https://ourworldindata.org/trade-and-income-inequality)|
|||4. PBS Documentary "Commanding Heights"|
|||**Respond to Classmates' Posts by February 22nd, (5pm)**|
|||**Quiz #3 due February 26th (5pm)**|
|||**Discussion Board #3 due March 5th (5pm)**|
||||
|5|March 8 - March 12|**Midterm Exam #1**|
||||||**Respond to Classmates' Posts by March, 8th (5pm)**|
||||
|6|March 15 - March 26| **Politics of International Finance**|
|||1. Read Jensen (see Canvas), pages 2-12|
|||2. Read [Isidore](https://www.cnn.com/2019/08/13/economy/foreign-direct-investment-china-us/index.html)|
|||3. Read [Chatzky and McBride](https://www.cfr.org/backgrounder/chinas-massive-belt-and-road-initiative)|
|||4. Watch [BBC Documentary](https://www.youtube.com/watch?v=OMx_ncuoSzQ)|
|||5. Read Oatley, pages 241-242.|
|||**Group Policy Brief due March 17th (5 pm)**|
|||**Discussion Board #4 due March 26th (5pm)**|
||||
||March 29 - April 2| **Spring Recess**|
||||
|7|April 5 - April 16| **Political Economy of Financial Crises**|
|||1.Read [Amadeo](https://www.thebalance.com/2008-financial-crisis-3305679)|
|||2. Podcast ["The Price of Default"](https://www.npr.org/sections/money/2011/10/14/141365144/friday-podcast-the-price-of-default)|
|||3. Documentary "The Big Short"|
|||4. [The Euro and Greek Crisis](https://www.youtube.com/watch?v=ULQiCN0YNmw)|
|||**Respond to Classmates' Posts by April 5th, (5pm)**|
|||**Quiz #4 due April 9th (5pm)**|
|||**Discussion Board #4 due April 16th (5pm)**|
||||
|8|April 19 - April 30| **The Global Economy in the 21st Century**|
|||1. Read Goldman Sachs |
|||2. Read Barma and Ratner |
|||3. Read [Greenwald](https://www.atlanticcouncil.org/blogs/new-atlanticist/achieving-supply-chain-independence-in-a-post-covid-economy/)|
|||4. Read [Mankiw](. http://gregmankiw.blogspot.com/2007/04/case-for-small-carbon-tax.html)|
|||**Respond to Classmates' Posts by April 19th, (5pm)**|
|||**Quiz #5 due April 22nd (5pm)**|
|||**Discussion Board #5 due April 30th (5pm)**|
||||
|9|May 3 - May 7|**Exam #2**|
||||
|10|May 10 - May 15| **Wellness Week**|
||||
|11| May 19| **Group Policy Brief #2**|
